# Proyecto Final - Analisis de Tiempo dedicado a Lectura

In [76]:
import pandas as pd
import os

### Carga de datos

In [77]:
df = pd.read_csv('conjunto_de_datos_enut_2019_csv/conjunto_de_datos_tmodulo_enut_2019/conjunto_de_datos/conjunto_de_datos_tmodulo_enut_2019.csv')

In [78]:
columns = ['CVE_ENT', 'SEXO', 'EDAD_V', 'TLOC', 'NIV', 'GRA', 
           'P6_22_4', 'P6_22A_4_1', 'P6_22A_4_2', 'P6_22A_4_3', 'P6_22A_4_4',]

In [79]:
df = df[columns]

In [80]:
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71404 entries, 0 to 71403
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CVE_ENT     71404 non-null  int64
 1   SEXO        71404 non-null  int64
 2   EDAD_V      71404 non-null  int64
 3   TLOC        71404 non-null  int64
 4   NIV         71404 non-null  int64
 5   GRA         71404 non-null  int64
 6   P6_22_4     71404 non-null  int64
 7   P6_22A_4_1  16912 non-null  float64
 8   P6_22A_4_2  16912 non-null  float64
 9   P6_22A_4_3  16912 non-null  float64
 10  P6_22A_4_4  16912 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 6.0 MB
None

,CVE_ENT,SEXO,EDAD_V,TLOC,NIV,GRA,P6_22_4,P6_22A_4_1,P6_22A_4_2,P6_22A_4_3,P6_22A_4_4
0,1,2,37,1,3,3,2,NaN,NaN,NaN,NaN
1,1,1,67,1,8,2,2,NaN,NaN,NaN,NaN
2,1,2,60,1,3,3,1,0.0,50.0,0.0,20.0
3,1,1,29,1,8,5,1,0.0,0.0,1.0,0.0
4,1,1,69,1,2,3,2,NaN,NaN,NaN,NaN

### Seleccion de variales de interes

In [81]:
df.dropna(subset=['P6_22_4', 'P6_22A_4_1', 'P6_22A_4_2', 'P6_22A_4_3', 'P6_22A_4_4'], inplace=True)

In [86]:
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 16912 entries, 2 to 71400
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   clave_entidad             16912 non-null  object
 1   sexo                      16912 non-null  object
 2   edad                      16912 non-null  int64
 3   tamaño_localidad          16912 non-null  object
 4   nivel_educativo           16912 non-null  object
 5   grado_maximo_aprobado     16912 non-null  int64
 6   ha_leido                  16912 non-null  object
 7   horas_lunes_viernes       16912 non-null  float64
 8   minutos_lunes_viernes     16912 non-null  float64
 9   material_lectura_mensual  16912 non-null  float64
 10  material_lectura_anual    16912 non-null  float64
dtypes: float64(4), int64(2), object(5)
memory usage: 1.5+ MB
None

,clave_entidad,sexo,edad,tamaño_localidad,nivel_educativo,grado_maximo_aprobado,ha_leido,horas_lunes_viernes,minutos_lunes_viernes,material_lectura_mensual,material_lectura_anual
2,Aguascalientes,Mujer,60,Localidades con 100 000 y más habitantes,Secundaria,3,Sí,0.0,50.0,0.0,20.0
3,Aguascalientes,Hombre,29,Localidades con 100 000 y más habitantes,Licenciatura o ingeniería (profesional),5,Sí,0.0,0.0,1.0,0.0
5,Aguascalientes,Mujer,68,Localidades con 100 000 y más habitantes,Primaria,6,Sí,10.0,0.0,0.0,0.0
6,Aguascalientes,Mujer,62,Localidades con 100 000 y más habitantes,Primaria,6,Sí,1.0,0.0,1.0,0.0
9,Aguascalientes,Hombre,71,Localidades con 100 000 y más habitantes,Primaria,6,Sí,5.0,0.0,0.0,0.0

### Reemplazar códigos con descripciones de catálogos

In [83]:
# Ruta base de los catálogos
catalogos_path = 'conjunto_de_datos_enut_2019_csv/conjunto_de_datos_tmodulo_enut_2019/catalogos'

# Columnas con catálogos
columnas_con_catalogo = ['CVE_ENT', 'SEXO', 'TLOC', 'NIV', 'P6_22_4']

# Reemplazar valores usando los catálogos
for col in columnas_con_catalogo:
    catalogo_file = os.path.join(catalogos_path, f'{col.lower()}.csv')
    
    if os.path.exists(catalogo_file):
        # Leer catálogo
        catalogo = pd.read_csv(catalogo_file)
        
        # Crear diccionario de mapeo
        mapeo = dict(zip(catalogo['cve'], catalogo['descrip']))
        
        # Reemplazar valores en el dataframe
        df[col] = df[col].map(mapeo)
        
        print(f"✓ Columna '{col}' reemplazada con catálogo '{col.lower()}.csv'")
    else:
        print(f"✗ No se encontró el archivo '{col.lower()}.csv'")

✓ Columna 'CVE_ENT' reemplazada con catálogo 'cve_ent.csv'
✓ Columna 'SEXO' reemplazada con catálogo 'sexo.csv'
✓ Columna 'TLOC' reemplazada con catálogo 'tloc.csv'
✓ Columna 'NIV' reemplazada con catálogo 'niv.csv'
✓ Columna 'P6_22_4' reemplazada con catálogo 'p6_22_4.csv'

### Renombrar columnas

In [84]:
columns_mapping = {
    'CVE_ENT': 'clave_entidad',
    'SEXO': 'sexo',
    'EDAD_V': 'edad',
    'TLOC': 'tamaño_localidad',
    'NIV': 'nivel_educativo',
    'GRA': 'grado_maximo_aprobado',
    'P6_22_4': 'ha_leido',
    'P6_22A_4_1': 'horas_lunes_viernes',
    'P6_22A_4_2': 'minutos_lunes_viernes',
    'P6_22A_4_3': 'material_lectura_mensual',
    'P6_22A_4_4': 'material_lectura_anual',
}

df.rename(columns=columns_mapping, inplace=True)

In [85]:
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 16912 entries, 2 to 71400
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   clave_entidad             16912 non-null  object
 1   sexo                      16912 non-null  object
 2   edad                      16912 non-null  int64
 3   tamaño_localidad          16912 non-null  object
 4   nivel_educativo           16912 non-null  object
 5   grado_maximo_aprobado     16912 non-null  int64
 6   ha_leido                  16912 non-null  object
 7   horas_lunes_viernes       16912 non-null  float64
 8   minutos_lunes_viernes     16912 non-null  float64
 9   material_lectura_mensual  16912 non-null  float64
 10  material_lectura_anual    16912 non-null  float64
dtypes: float64(4), int64(2), object(5)
memory usage: 1.5+ MB
None

,clave_entidad,sexo,edad,tamaño_localidad,nivel_educativo,grado_maximo_aprobado,ha_leido,horas_lunes_viernes,minutos_lunes_viernes,material_lectura_mensual,material_lectura_anual
2,Aguascalientes,Mujer,60,Localidades con 100 000 y más habitantes,Secundaria,3,Sí,0.0,50.0,0.0,20.0
3,Aguascalientes,Hombre,29,Localidades con 100 000 y más habitantes,Licenciatura o ingeniería (profesional),5,Sí,0.0,0.0,1.0,0.0
5,Aguascalientes,Mujer,68,Localidades con 100 000 y más habitantes,Primaria,6,Sí,10.0,0.0,0.0,0.0
6,Aguascalientes,Mujer,62,Localidades con 100 000 y más habitantes,Primaria,6,Sí,1.0,0.0,1.0,0.0
9,Aguascalientes,Hombre,71,Localidades con 100 000 y más habitantes,Primaria,6,Sí,5.0,0.0,0.0,0.0

### Analisis exploratorio de datos (EDA)